# Generated by Django 4.0.3 on 2022-06-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_product_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
