# Generated by Django 4.0.3 on 2022-06-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_description_item_desc_rename_name_item_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
