# Generated by Django 4.0.3 on 2022-06-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='origin',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default='Veg', max_length=9),
        ),
    ]
