# Generated by Django 4.0.3 on 2022-06-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_origin_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='preparation_time',
            field=models.IntegerField(default=0),
        ),
    ]
