# Generated by Django 4.0.3 on 2022-06-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_item_preparation_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
