# Generated by Django 4.0.3 on 2022-06-04 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('tableNo', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order')),
            ],
        ),
    ]
