# Generated by Django 4.0.3 on 2022-06-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='/Kadai-Paneer.jpg', null=True, upload_to=''),
        ),
    ]
