# Generated by Django 4.0.3 on 2022-06-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_tableinfo_user_tableinfo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableinfo',
            name='availabilty_status',
            field=models.BooleanField(default=True),
        ),
    ]
