# Generated by Django 4.0.3 on 2022-06-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_tableinfo_availabilty_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='preparation_time',
            new_name='preparationTime',
        ),
    ]
