# Generated by Django 4.0.3 on 2022-06-09 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_preparation_time_item_preparationtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='item',
        ),
    ]
