# Generated by Django 4.0.3 on 2022-06-09 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_tableinfo_currentorder_currentorder_tableinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentorder',
            name='tableInfo',
        ),
        migrations.AddField(
            model_name='tableinfo',
            name='currentOrder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.currentorder'),
        ),
    ]
