# Generated by Django 4.0.3 on 2022-06-09 14:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0025_rename_currentorder_current'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Current',
            new_name='CurrentOrder',
        ),
    ]
